on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 13 * * * '
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
          cache: "npm"
      - name: Run NPM Outdated
        run: |
          npx check
