name: Publish

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: npm ci
      - name: Githup Package Publish
        run: |
          npm publish
          npm version
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
